/**
 * Brand aliases — Arabic ↔ English bidirectional mapping for SearchableSelect.
 *
 * الـ user بيدخل الماركة بأي شكل (عربي / إنجليزي / transliteration)،
 * والـ dropdown لازم يظهر نفس الـ result سواء كتب "Mercedes" أو "مرسيدس".
 *
 * الـ key هو الـ canonical name من الـ catalog (case-insensitive lookup) —
 * الـ value هو list الـ alternative names (Arabic + alternative English forms).
 *
 * Mapping rules:
 *  - الـ lookup بيتم بـ exact key match (case-insensitive) أو بـ lowercased key.
 *  - الـ aliases بتتعمل includes() على الـ query (lowercased) — فلو الـ query
 *    "مرسيدس" موجود كـ alias للـ "Mercedes"، الـ dropdown يظهر Mercedes.
 *  - لو الـ brand مش في الـ map، الـ search بيشتغل على الـ label بس (السلوك
 *    القديم).
 *  - الـ aliases مش exclusive — لو الـ brand له aliases تانية في الـ DB
 *    (مثلاً "BMW" و "Bmw" و "بي ام")، الـ user بيشوفهم كلهم في الـ dropdown.
 *
 * Generated by hand for the most common Arabic ↔ English pairs in the Egyptian
 * market. To extend, just add a new entry below — the SearchableSelect picks
 * it up automatically.
 */

// ============================================================================
// Lookup table
// ============================================================================

const BRAND_ALIASES: Record<string, readonly string[]> = {
  // ─── German luxury ───────────────────────────────────────────────────────
  Mercedes: ['مرسيدس', 'مرسيديز', 'بنز', 'مارسيدس'],
  'Mercedes-Benz': ['مرسيدس', 'مرسيديز', 'بنز', 'مارسيدس', 'Mercedes'],
  BMW: ['بي ام', 'بي إم', 'بي ام دبليو', 'بي إم دبليو', 'بى إم'],
  Bmw: ['بي ام', 'بي إم', 'بي ام دبليو', 'بي إم دبليو', 'بى إم', 'BMW'],
  Audi: ['أودي', 'اودي'],
  Volkswagen: ['فولكس', 'فولكس فاجن', 'فولكس فاجن'],
  Porsche: ['بورش', 'بورشه'],
  Opel: ['أوبل', 'اوبل'],
  Mini: ['ميني'],
  Smart: ['سمارت'],

  // ─── Italian ──────────────────────────────────────────────────────────────
  Fiat: ['فيات', 'فيات'],
  'Alfa Romeo': ['ألفا روميو', 'الفا روميو', 'ألفا'],
  Ferrari: ['فيراري'],
  Lamborghini: ['لامبورجيني', 'لامبورغيني'],
  Maserati: ['مازيراتي', 'مازيراتي'],
  Lancia: ['لانشيا'],
  Abarth: ['أبارث', 'ابارث', 'ابارث'],

  // ─── British ──────────────────────────────────────────────────────────────
  'Rolls-Royce': ['رولز رويز', 'رولزرويز'],
  Bentley: ['بنتلي', 'بنتلى'],
  'Aston Martin': ['استون مارتن', 'أستون مارتن', 'استون مارتن'],
  McLaren: ['ماكلارين'],
  Lotus: ['لوتس'],
  Jaguar: ['جاكوار', 'جاكوار'],

  // ─── French ──────────────────────────────────────────────────────────────
  Peugeot: ['بيجو', 'بيجو'],
  Renault: ['رينو', 'رونو', 'رينو'],
  Renaul: ['رينو', 'رونو', 'Renault'],
  Citroën: ['ستروين', 'سيتروين', 'ستروين'],
  Citroen: ['ستروين', 'سيتروين', 'Citroën', 'ستروين'],
  citroen: ['ستروين', 'سيتروين', 'Citroën', 'ستروين', 'Citroen'],
  DS: ['دي اس', 'دي إس'],
  Bugatti: ['بوغاتي', 'بوجاتي'],

  // ─── American ────────────────────────────────────────────────────────────
  Ford: ['فورد', 'فورد'],
  ford: ['فورد', 'Ford'],
  Chevrolet: ['شيفروليه', 'شيفروليه'],
  Dodge: ['دودج'],
  Chrysler: ['كرايسلر', 'كرايسلر'],
  Cadillac: ['كاديلاك', 'كاديلاك'],
  Buick: ['بيوك'],
  GMC: ['جي ام سي', 'جي إم سي'],
  Lincoln: ['لينكولن'],
  Tesla: ['تسلا'],
  Hummer: ['هامر', 'هامر'],
  Pontiac: ['بونتياك'],
  Mercury: ['ميركوري'],
  Scion: ['سيون'],

  // ─── Japanese ────────────────────────────────────────────────────────────
  Toyota: ['تويوتا', 'تويوتا'],
  Nissan: ['نيسان', 'نيسان'],
  Honda: ['هوندا'],
  Mazda: ['مازدا'],
  Mitsubishi: ['ميتسوبيشي', 'ميتسوبيشي'],
  Suzuki: ['سوزوكي'],
  Subaru: ['سوبارو'],
  Lexus: ['لكزس', 'لكسز'],
  Infiniti: ['انفينيتي', 'إنفينيتي', 'انفينيتي'],
  Acura: ['أكورا', 'أكورا'],
  Daihatsu: ['دايهاتسو', 'دايهاتسو'],
  Isuzu: ['إيسوزو', 'ايسوزو'],

  // ─── Korean ──────────────────────────────────────────────────────────────
  Hyundai: ['هيونداي', 'هونداي', 'هيونداي'],
  Kia: ['كيا'],
  SsangYong: ['سانج', 'سانج يونج', 'سانج يونغ', 'SsangYong'],

  // ─── Chinese ─────────────────────────────────────────────────────────────
  Geely: ['جيلي'],
  Chery: ['شيري', 'شيري'],
  MG: ['ام جي', 'إم جي', 'ام جى', 'إم جى'],
  Mg: ['ام جي', 'إم جي', 'ام جى', 'إم جى', 'MG'],
  Jetour: ['جيتور'],
  Exeed: ['إكسييد', 'اكسييد'],
  Omoda: ['أومودا', 'اومودا'],
  Polestar: ['بولستار'],
  Cupra: ['كوبرا'],
  Bestune: ['بيستون'],
  Borgward: ['بورجوارد'],
  Brilliance: ['بريليانس', 'بريليانس'],
  Changan: ['تشانجان'],
  BYD: ['بي واي دي'],
  Haval: ['هافال'],
  Chana: ['تشانا'],
  Datsun: ['داتسون'],
  Dayun: ['دايون'],
  Deepal: ['ديبال'],
  DFSK: ['دي اف اس كيه', 'دي إف إس كيه'],
  Dorcen: ['دورسين'],
  Emgrand: ['إمجراند'],
  Forthing: ['فورثينج'],
  Foton: ['فوتون'],
  Fuso: ['فوسو'],
  GAC: ['جي ايه سي', 'جي إيه سي'],
  GAZ: ['جاز'],
  'Golden Dragon': ['جولدن دراجون', 'غولدن دراغون'],
  'Great Wall': ['جريت وول', 'غريت وول'],
  Hafei: ['هافي'],
  Haima: ['هايما', 'هايما'],
  Halawa: ['حلاوة'],
  Hanteng: ['هانتنج'],
  Haojiang: ['هاوجيانج'],
  Haojue: ['هاوجوي'],
  Hawtai: ['هاوتاي'],
  Hongqi: ['هونج تشي', 'هونغتشي'],
  IM: ['آي إم'],
  Ineos: ['إينيوس'],
  JAC: ['جاك'],
  JMC: ['جي ام سي', 'جي إم سي'],
  Kaiyi: ['كايي'],
  Karry: ['كاري'],
  Keeway: ['كيواي'],
  Keyton: ['كيتون'],
  KGM: ['كي جي إم'],
  'King Long': ['كينج لونج'],
  Leapmotor: ['ليبموتور'],
  'Li Auto': ['لي أوتو'],
  Lifan: ['ليفان'],
  LML: ['إل إم إل'],
  Maxus: ['ماكسوس'],
  Rox: ['روكس'],
  Saab: ['ساب'],
  Saipa: ['سايبا'],
  Shineray: ['شينيراي'],
  Skywell: ['سكايويل'],
  Sokon: ['سوكون'],
  Soueast: ['سويست'],
  Speranza: ['سبيرانزا'],
  Tank: ['تانك'],
  TVS: ['تي في إس'],
  Victory: ['فيكتوري'],
  Wuling: ['وولينج'],
  Xiaomi: ['شاومي', 'زياومي'],
  Xpeng: ['إكس بنج', 'إكسبينغ'],
  Yamaha: ['ياماها'],
  Zeekr: ['زيكر'],
  Zotye: ['زوتي'],

  // ─── Indian + SEA + others ──────────────────────────────────────────────
  Mahindra: ['ماهيندرا'],
  Tata: ['تاتا'],
  Proton: ['بروتون'],
  Perodua: ['بيرودوا'],
  Bajaj: ['باجاج'],
  Benelli: ['بينيلي'],
  Ducati: ['دوكاتي'],
  Kymco: ['كايمكو'],
  Sym: ['سيم'],
};

// ============================================================================
// Public API
// ============================================================================

/**
 * Returns the aliases for a given brand label. Lookup is case-insensitive —
 * so "Mercedes", "mercedes", "MERCEDES" all return the same alias list.
 * Returns `undefined` لو الـ brand مش في الـ alias map (الـ caller يستخدم
 * الـ default label-only search في الحالة دي).
 */
export function getBrandAliases(label: string): readonly string[] | undefined {
  return BRAND_ALIASES[label] ?? BRAND_ALIASES[label.toLowerCase()];
}