/**
 * Comprehensive catalog of car brands, models, years, and paints.
 *
 * Combines:
 *   1. 151 brand logos from the Flutter app (`assets/brand_logos/*.png`) — slugs
 *      like `toyota.png`, `bmw.png`. Auto-converted to Title Case with overrides
 *      for multi-word brands and special characters.
 *   2. Brands/models/years/paints parsed from the Firestore `cars` collection
 *      (via scripts/parse-cars-catalog.mjs → carsCatalog.generated.json).
 *
 * Generated by scripts/parse-cars-catalog.mjs — re-run that script to refresh
 * the Firestore-derived portion. The Flutter slug list is hand-maintained below.
 */

// ---------------------------------------------------------------------------
// Flutter brand slugs (lowercase, snake_case). Sourced from
// `D:\Programming\Projects\Flutter\car_app\assets\brand_logos\*.png`.
// ---------------------------------------------------------------------------

export const FLUTTER_BRAND_SLUGS: readonly string[] = [
  'abarth',
  'acura',
  'aito',
  'alfa_romeo',
  'arcfox',
  'aston_martin',
  'audi',
  'avatr',
  'baic',
  'bajaj',
  'benelli',
  'bentley',
  'bestune',
  'bmw',
  'borgward',
  'brilliance',
  'bugatti',
  'buick',
  'byd',
  'cadillac',
  'chana',
  'changan',
  'chery',
  'chevrolet',
  'chrysler',
  'citro_n',
  'citroen',
  'cupra',
  'daewoo',
  'daihatsu',
  'datsun',
  'dayun',
  'deepal',
  'dfsk',
  'dodge',
  'dongfeng',
  'dorcen',
  'ds',
  'ducati',
  'emgrand',
  'exeed',
  'faw',
  'ferrari',
  'fiat',
  'ford',
  'forthing',
  'foton',
  'fuso',
  'gac',
  'gaz',
  'geely',
  'genesis',
  'gmc',
  'golden_dragon',
  'great_wall',
  'hafei',
  'haima',
  'halawa',
  'hanteng',
  'haojiang',
  'haojue',
  'haval',
  'hawtai',
  'honda',
  'hongqi',
  'hummer',
  'hyundai',
  'im',
  'ineos',
  'infiniti',
  'isuzu',
  'jac',
  'jaguar',
  'jeep',
  'jetour',
  'jinbei',
  'jmc',
  'kaiyi',
  'karry',
  'keeway',
  'keyton',
  'kgm',
  'kia',
  'king_long',
  'kymco',
  'lada',
  'lamborghini',
  'lancia',
  'land_rover',
  'landwind',
  'leapmotor',
  'lexus',
  'li_auto',
  'lifan',
  'lincoln',
  'lml',
  'lotus',
  'lynkco',
  'mahindra',
  'maserati',
  'maxus',
  'mazda',
  'mclaren',
  'mercedes',
  'mercury',
  'mg',
  'mini',
  'mitsubishi',
  'nissan',
  'omoda',
  'opel',
  'perodua',
  'peugeot',
  'polestar',
  'pontiac',
  'porsche',
  'proton',
  'pullman',
  'renault',
  'rolls_royce',
  'rox',
  'saab',
  'saipa',
  'sandstorm',
  'scion',
  'seat',
  'shineray',
  'skoda',
  'skywell',
  'smart',
  'sokon',
  'soueast',
  'speranza',
  'ssang_yong',
  'subaru',
  'suzuki',
  'sym',
  'tank',
  'tata',
  'tesla',
  'toyota',
  'tvs',
  'victory',
  'volkswagen',
  'volvo',
  'wuling',
  'xiaomi',
  'xpeng',
  'yamaha',
  'zeekr',
  'zotye',
];

/** Special-cased slug → display name mappings for multi-word or unicode brands. */
const SLUG_OVERRIDES: Record<string, string> = {
  alfa_romeo: 'Alfa Romeo',
  aston_martin: 'Aston Martin',
  citro_n: 'Citroën',
  citroen: 'Citroën',
  golden_dragon: 'Golden Dragon',
  great_wall: 'Great Wall',
  king_long: 'King Long',
  land_rover: 'Land Rover',
  li_auto: 'Li Auto',
  rolls_royce: 'Rolls-Royce',
  ssang_yong: 'SsangYong',
};

/** Convert a Flutter brand slug to a display name (Title Case by default). */
function slugToBrandName(slug: string): string {
  if (SLUG_OVERRIDES[slug]) return SLUG_OVERRIDES[slug];
  return slug
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// ---------------------------------------------------------------------------
// Firestore-derived catalog (generated by scripts/parse-cars-catalog.mjs).
// ---------------------------------------------------------------------------

import catalogData from './carsCatalog.generated.json';
import { BRANDS as STATIC_BRANDS } from './carBrands';

interface CatalogData {
  brands?: string[];
  modelsByBrand?: Record<string, string[]>;
  yearsByBrandModel?: Record<string, number[]>;
  paintByBrandModelYear?: Record<string, string[]>;
}

const firestoreCatalog = catalogData as CatalogData;

const FLUTTER_BRANDS: string[] = FLUTTER_BRAND_SLUGS.map(slugToBrandName);

// Union Flutter brands + Firestore-derived brands, dedup case-insensitively,
// sorted. The Firestore portion can include Arabic brand names that aren't in
// the Flutter catalog — those get appended (no logo, but still selectable).
const allBrands: string[] = (() => {
  const byLower = new Map<string, string>();
  for (const b of FLUTTER_BRANDS) byLower.set(b.toLowerCase(), b);
  for (const b of firestoreCatalog.brands ?? []) {
    const k = b.toLowerCase();
    if (!byLower.has(k)) byLower.set(k, b);
  }
  return Array.from(byLower.values()).sort((a, b) => a.localeCompare(b));
})();

// ---------------------------------------------------------------------------
// Static model catalog — carBrands.ts يحتوي على models شاملة لأكثر من 30 ماركة
// معروفة في السوق المصري (Toyota, BMW, BYD, Abarth-like cases, إلخ).
// الـ lookup هنا case-insensitive مع alias mapping عشان:
//   - "Mercedes" (من الـ catalog) → "Mercedes-Benz" (من carBrands)
//   - "BMW" / "Bmw" → "BMW"
//   - "MG" / "Mg" → "MG"
// ---------------------------------------------------------------------------

const STATIC_MODELS_BY_CANONICAL: Record<string, string[]> = (() => {
  const out: Record<string, string[]> = {};
  for (const b of STATIC_BRANDS) {
    out[b.name.toLowerCase()] = [...b.models];
  }
  return out;
})();

// Mapping من الأسماء الموجودة في الـ catalog لـ canonical carBrands keys.
// بنغطي الـ variations الشائعة (case, dash, etc.) + الـ aliases في brandAliases.
const BRAND_TO_STATIC_KEY: Record<string, string> = {
  'mercedes': 'mercedes-benz',
  'mercedes-benz': 'mercedes-benz',
  'bmw': 'bmw',
  'land rover': 'land rover',
  'land_rover': 'land rover',
  'rolls royce': 'rolls-royce',
  'rolls-royce': 'rolls-royce',
  'rolls_royce': 'rolls-royce',
  'alfa romeo': 'alfa romeo',
  'alfa_romeo': 'alfa romeo',
  'aston martin': 'aston martin',
  'aston_martin': 'aston martin',
  'ssangyong': 'ssangyong',
  'ssang_yong': 'ssangyong',
  'ssang-yong': 'ssangyong',
  'landwind': 'landwind',
  'land wind': 'landwind',
  'land_wind': 'landwind',
  'li auto': 'li auto',
  'li_auto': 'li auto',
  'king long': 'king long',
  'king_long': 'king long',
  'golden dragon': 'golden dragon',
  'golden_dragon': 'golden dragon',
  'great wall': 'great wall',
  'great_wall': 'great wall',
  'mg': 'mg',
};

/**
 * Resolve any brand name (from catalog or user input) to a carBrands key.
 * Returns the lowercased key or null لو الـ brand مش في carBrands.
 */
function resolveStaticBrandKey(brand: string): string | null {
  const lower = brand.toLowerCase().trim();
  // 1. direct map
  if (BRAND_TO_STATIC_KEY[lower]) return BRAND_TO_STATIC_KEY[lower];
  // 2. direct lookup in static catalog (case-insensitive)
  if (STATIC_MODELS_BY_CANONICAL[lower]) return lower;
  // 3. try with underscores replaced (Flutter slug form)
  const withSpaces = lower.replace(/_/g, ' ');
  if (STATIC_MODELS_BY_CANONICAL[withSpaces]) return withSpaces;
  // 4. try with spaces replaced by underscores
  const withUnderscores = lower.replace(/ /g, '_');
  if (STATIC_MODELS_BY_CANONICAL[withUnderscores]) return withUnderscores;
  return null;
}

// Models per brand — combined source:
//   1. Static carBrands models (comprehensive, hand-curated for popular brands)
//   2. Firestore-derived models (DB entries with that exact brand name)
// الـ static data بيغطي ~30 ماركة معروفة (Toyota, BMW, BYD, Abarth-like cases, etc.)
// حتى لو الـ DB فاضي. الـ Firestore data بيزوّد على الـ static بـ models الـ user
// أضافها قبل كده (free-text).
const allModelsByBrand: Record<string, string[]> = {};
for (const brand of allBrands) {
  const set = new Set<string>();
  // Static models (comprehensive)
  const staticKey = resolveStaticBrandKey(brand);
  if (staticKey && STATIC_MODELS_BY_CANONICAL[staticKey]) {
    for (const m of STATIC_MODELS_BY_CANONICAL[staticKey]) set.add(m);
  }
  // Firestore-derived models (case-insensitive lookup)
  for (const [dbBrand, dbModels] of Object.entries(
    firestoreCatalog.modelsByBrand ?? {}
  )) {
    if (dbBrand.toLowerCase() === brand.toLowerCase()) {
      for (const m of dbModels) set.add(m);
    }
  }
  allModelsByBrand[brand] = Array.from(set).sort();
}

export const CARS_CATALOG = {
  brands: allBrands,
  modelsByBrand: allModelsByBrand,
  yearsByBrandModel: firestoreCatalog.yearsByBrandModel ?? {},
  paintByBrandModelYear: firestoreCatalog.paintByBrandModelYear ?? {},
};

export function getModelsForBrand(brand: string): string[] {
  // Try direct lookup first (case-insensitive)
  const direct = CARS_CATALOG.modelsByBrand[brand];
  if (direct && direct.length > 0) return direct;
  // Fallback: try resolving via the static key resolver
  const lower = brand.toLowerCase().trim();
  for (const [catalogBrand, models] of Object.entries(CARS_CATALOG.modelsByBrand)) {
    if (catalogBrand.toLowerCase() === lower && models.length > 0) {
      return models;
    }
  }
  return [];
}

export function getYearsForBrandModel(brand: string, model: string): number[] {
  return CARS_CATALOG.yearsByBrandModel[`${brand}::${model}`] ?? [];
}

const DEFAULT_PAINT_OPTIONS = ['فبريكا'];
const DEFAULT_MAINTENANCE_OPTIONS = ['في التوكيل', 'بره التوكيل', 'مختلط'];

/**
 * Returns paint options for the brand/model/year combination.
 * Always includes "فبريكا" + "أخرى" sentinels (the form maps "أخرى" to a
 * free-text input). Falls back to just "فبريكا" when no data exists.
 */
export function getPaintForBrandModelYear(
  brand: string,
  model: string,
  year: number
): string[] {
  const fromData = CARS_CATALOG.paintByBrandModelYear[`${brand}::${model}::${year}`];
  if (fromData && fromData.length > 0) {
    // dedup + sort + ensure "فبريكا" is first if present
    const set = new Set<string>(fromData);
    if (set.has('فبريكا')) set.delete('فبريكا');
    return ['فبريكا', ...Array.from(set).sort()];
  }
  return DEFAULT_PAINT_OPTIONS;
}

/**
 * Returns maintenance options — currently the Firestore catalog doesn't have
 * maintenance data, so we always return the standard 3 options.
 */
export function getMaintenanceForBrandModelYear(
  _brand: string,
  _model: string,
  _year: number
): string[] {
  return DEFAULT_MAINTENANCE_OPTIONS;
}

export function getAllBrandNames(): string[] {
  return CARS_CATALOG.brands;
}

// Re-export the default fallback arrays for direct imports.
export { DEFAULT_PAINT_OPTIONS, DEFAULT_MAINTENANCE_OPTIONS };