/**
 * Comprehensive catalog of car brands, models, years, and paints.
 *
 * Combines:
 *   1. 151 brand logos from the Flutter app (`assets/brand_logos/*.png`) — slugs
 *      like `toyota.png`, `bmw.png`. Auto-converted to Title Case with overrides
 *      for multi-word brands and special characters.
 *   2. Brands/models/years/paints parsed from the Firestore `cars` collection
 *      (via scripts/parse-cars-catalog.mjs → carsCatalog.generated.json).
 *
 * Generated by scripts/parse-cars-catalog.mjs — re-run that script to refresh
 * the Firestore-derived portion. The Flutter slug list is hand-maintained below.
 */

// ---------------------------------------------------------------------------
// Flutter brand slugs (lowercase, snake_case). Sourced from
// `D:\Programming\Projects\Flutter\car_app\assets\brand_logos\*.png`.
// ---------------------------------------------------------------------------

export const FLUTTER_BRAND_SLUGS: readonly string[] = [
  'abarth',
  'acura',
  'aito',
  'alfa_romeo',
  'arcfox',
  'aston_martin',
  'audi',
  'avatr',
  'baic',
  'bajaj',
  'benelli',
  'bentley',
  'bestune',
  'bmw',
  'borgward',
  'brilliance',
  'bugatti',
  'buick',
  'byd',
  'cadillac',
  'chana',
  'changan',
  'chery',
  'chevrolet',
  'chrysler',
  'citro_n',
  'citroen',
  'cupra',
  'daewoo',
  'daihatsu',
  'datsun',
  'dayun',
  'deepal',
  'dfsk',
  'dodge',
  'dongfeng',
  'dorcen',
  'ds',
  'ducati',
  'emgrand',
  'exeed',
  'faw',
  'ferrari',
  'fiat',
  'ford',
  'forthing',
  'foton',
  'fuso',
  'gac',
  'gaz',
  'geely',
  'genesis',
  'gmc',
  'golden_dragon',
  'great_wall',
  'hafei',
  'haima',
  'halawa',
  'hanteng',
  'haojiang',
  'haojue',
  'haval',
  'hawtai',
  'honda',
  'hongqi',
  'hummer',
  'hyundai',
  'im',
  'ineos',
  'infiniti',
  'isuzu',
  'jac',
  'jaguar',
  'jeep',
  'jetour',
  'jinbei',
  'jmc',
  'kaiyi',
  'karry',
  'keeway',
  'keyton',
  'kgm',
  'kia',
  'king_long',
  'kymco',
  'lada',
  'lamborghini',
  'lancia',
  'land_rover',
  'landwind',
  'leapmotor',
  'lexus',
  'li_auto',
  'lifan',
  'lincoln',
  'lml',
  'lotus',
  'lynkco',
  'mahindra',
  'maserati',
  'maxus',
  'mazda',
  'mclaren',
  'mercedes',
  'mercury',
  'mg',
  'mini',
  'mitsubishi',
  'nissan',
  'omoda',
  'opel',
  'perodua',
  'peugeot',
  'polestar',
  'pontiac',
  'porsche',
  'proton',
  'pullman',
  'renault',
  'rolls_royce',
  'rox',
  'saab',
  'saipa',
  'sandstorm',
  'scion',
  'seat',
  'shineray',
  'skoda',
  'skywell',
  'smart',
  'sokon',
  'soueast',
  'speranza',
  'ssang_yong',
  'subaru',
  'suzuki',
  'sym',
  'tank',
  'tata',
  'tesla',
  'toyota',
  'tvs',
  'victory',
  'volkswagen',
  'volvo',
  'wuling',
  'xiaomi',
  'xpeng',
  'yamaha',
  'zeekr',
  'zotye',
];

/** Special-cased slug → display name mappings for multi-word or unicode brands. */
const SLUG_OVERRIDES: Record<string, string> = {
  alfa_romeo: 'Alfa Romeo',
  aston_martin: 'Aston Martin',
  citro_n: 'Citroën',
  citroen: 'Citroën',
  golden_dragon: 'Golden Dragon',
  great_wall: 'Great Wall',
  king_long: 'King Long',
  land_rover: 'Land Rover',
  li_auto: 'Li Auto',
  rolls_royce: 'Rolls-Royce',
  ssang_yong: 'SsangYong',
};

/** Convert a Flutter brand slug to a display name (Title Case by default). */
function slugToBrandName(slug: string): string {
  if (SLUG_OVERRIDES[slug]) return SLUG_OVERRIDES[slug];
  return slug
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// ---------------------------------------------------------------------------
// Firestore-derived catalog (generated by scripts/parse-cars-catalog.mjs).
// ---------------------------------------------------------------------------

import catalogData from './carsCatalog.generated.json';

interface CatalogData {
  brands?: string[];
  modelsByBrand?: Record<string, string[]>;
  yearsByBrandModel?: Record<string, number[]>;
  paintByBrandModelYear?: Record<string, string[]>;
}

const firestoreCatalog = catalogData as CatalogData;

const FLUTTER_BRANDS: string[] = FLUTTER_BRAND_SLUGS.map(slugToBrandName);

// Union Flutter brands + Firestore-derived brands, dedup case-insensitively,
// sorted. The Firestore portion can include Arabic brand names that aren't in
// the Flutter catalog — those get appended (no logo, but still selectable).
const allBrands: string[] = (() => {
  const byLower = new Map<string, string>();
  for (const b of FLUTTER_BRANDS) byLower.set(b.toLowerCase(), b);
  for (const b of firestoreCatalog.brands ?? []) {
    const k = b.toLowerCase();
    if (!byLower.has(k)) byLower.set(k, b);
  }
  return Array.from(byLower.values()).sort((a, b) => a.localeCompare(b));
})();

// Models per brand — Firestore catalog only (Flutter app doesn't ship models).
// If a brand has no Firestore data, we leave the array empty (free-text fallback
// still works via the existing safety net in MarketEntryForm).
const allModelsByBrand: Record<string, string[]> = {};
for (const brand of allBrands) {
  allModelsByBrand[brand] = [...(firestoreCatalog.modelsByBrand?.[brand] ?? [])].sort();
}

export const CARS_CATALOG = {
  brands: allBrands,
  modelsByBrand: allModelsByBrand,
  yearsByBrandModel: firestoreCatalog.yearsByBrandModel ?? {},
  paintByBrandModelYear: firestoreCatalog.paintByBrandModelYear ?? {},
};

export function getModelsForBrand(brand: string): string[] {
  return CARS_CATALOG.modelsByBrand[brand] ?? [];
}

export function getYearsForBrandModel(brand: string, model: string): number[] {
  return CARS_CATALOG.yearsByBrandModel[`${brand}::${model}`] ?? [];
}

const DEFAULT_PAINT_OPTIONS = ['فبريكا'];
const DEFAULT_MAINTENANCE_OPTIONS = ['في التوكيل', 'بره التوكيل', 'مختلط'];

/**
 * Returns paint options for the brand/model/year combination.
 * Always includes "فبريكا" + "أخرى" sentinels (the form maps "أخرى" to a
 * free-text input). Falls back to just "فبريكا" when no data exists.
 */
export function getPaintForBrandModelYear(
  brand: string,
  model: string,
  year: number
): string[] {
  const fromData = CARS_CATALOG.paintByBrandModelYear[`${brand}::${model}::${year}`];
  if (fromData && fromData.length > 0) {
    // dedup + sort + ensure "فبريكا" is first if present
    const set = new Set<string>(fromData);
    if (set.has('فبريكا')) set.delete('فبريكا');
    return ['فبريكا', ...Array.from(set).sort()];
  }
  return DEFAULT_PAINT_OPTIONS;
}

/**
 * Returns maintenance options — currently the Firestore catalog doesn't have
 * maintenance data, so we always return the standard 3 options.
 */
export function getMaintenanceForBrandModelYear(
  _brand: string,
  _model: string,
  _year: number
): string[] {
  return DEFAULT_MAINTENANCE_OPTIONS;
}

export function getAllBrandNames(): string[] {
  return CARS_CATALOG.brands;
}

// Re-export the default fallback arrays for direct imports.
export { DEFAULT_PAINT_OPTIONS, DEFAULT_MAINTENANCE_OPTIONS };